# Generated by Django 5.2.7 on 2025-11-30 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('why_it_fits_template', models.TextField(blank=True, help_text="Short explanation template, e.g. 'You enjoy maths and logical thinking, so engineering suits you.'")),
                ('suggested_exams_text', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='EducationStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('PRIMARY', 'Primary (Class 1-5)'), ('MIDDLE', 'Middle (Class 6-8)'), ('HIGH_SCHOOL', 'High School (Class 9-10)'), ('HIGHER_SECONDARY', 'Higher Secondary (Class 11-12)'), ('UG', 'Undergraduate'), ('PG', 'Postgraduate'), ('PROFESSIONAL', 'Working Professional'), ('COUNSELOR', 'Parent / Teacher / Counselor')], max_length=32, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('min_class', models.PositiveIntegerField(blank=True, null=True)),
                ('max_class', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='InterestCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SkillDifficulty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], max_length=16, unique=True)),
                ('label', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('SCIENCE', 'Science'), ('COMMERCE', 'Commerce'), ('ARTS', 'Arts'), ('VOCATIONAL', 'Vocational')], max_length=32, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
                ('pros', models.TextField(blank=True)),
                ('cons', models.TextField(blank=True)),
                ('required_strengths', models.TextField(blank=True)),
                ('key_subjects', models.TextField(blank=True)),
                ('early_preparation_ideas', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActivitySuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('focus_area', models.CharField(blank=True, max_length=64)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.educationstage')),
            ],
        ),
        migrations.CreateModel(
            name='MotivationTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('audience', models.CharField(choices=[('SCHOOL', 'School student'), ('UG_PG', 'UG/PG student'), ('PROFESSIONAL', 'Professional'), ('PARENT', 'Parent / Counselor')], max_length=32)),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recommender.educationstage')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('question_type', models.CharField(choices=[('INTEREST', 'Interest / Aptitude'), ('SUBJECT_STRENGTH', 'Subject Strength')], default='INTEREST', max_length=32)),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recommender.educationstage')),
            ],
        ),
        migrations.CreateModel(
            name='OptionScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=255)),
                ('logical_score', models.IntegerField(default=0)),
                ('analytical_score', models.IntegerField(default=0)),
                ('creative_score', models.IntegerField(default=0)),
                ('practical_score', models.IntegerField(default=0)),
                ('people_score', models.IntegerField(default=0)),
                ('scientific_score', models.IntegerField(default=0)),
                ('design_score', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='recommender.question')),
            ],
        ),
        migrations.CreateModel(
            name='SkillPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recommender.educationstage')),
                ('primary_stream', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recommender.stream')),
            ],
        ),
        migrations.CreateModel(
            name='SkillPathStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.PositiveIntegerField()),
                ('level', models.PositiveSmallIntegerField(choices=[(1, 'Level 1 - Foundations'), (2, 'Level 2 - Core'), (3, 'Level 3 - Tools / Frameworks'), (4, 'Level 4 - Projects / Deployment')])),
                ('estimated_weeks', models.PositiveIntegerField(default=2)),
                ('difficulty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recommender.skilldifficulty')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.skill')),
                ('skill_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='recommender.skillpath')),
            ],
            options={
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='RecommendationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('min_science_score', models.IntegerField(blank=True, null=True)),
                ('min_commerce_score', models.IntegerField(blank=True, null=True)),
                ('min_arts_score', models.IntegerField(blank=True, null=True)),
                ('priority', models.IntegerField(default=100)),
                ('primary_career', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recommender.career')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recommender.educationstage')),
                ('primary_skill_path', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recommender.skillpath')),
                ('recommended_stream', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recommender.stream')),
            ],
        ),
        migrations.AddField(
            model_name='career',
            name='stream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='careers', to='recommender.stream'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('current_class', models.PositiveIntegerField(blank=True, null=True)),
                ('current_role', models.CharField(blank=True, max_length=128)),
                ('target_role', models.CharField(blank=True, max_length=128)),
                ('is_parent_mode', models.BooleanField(default=False)),
                ('education_stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recommender.educationstage')),
            ],
        ),
        migrations.CreateModel(
            name='RecommendationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stage_snapshot', models.CharField(blank=True, max_length=64)),
                ('input_data', models.TextField(blank=True)),
                ('output_streams', models.TextField(blank=True)),
                ('output_careers', models.TextField(blank=True)),
                ('output_skill_paths', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recommender.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='UserSkillProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not started'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed')], default='NOT_STARTED', max_length=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skill_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.skillpath')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.skillpathstep')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.userprofile')),
            ],
            options={
                'unique_together': {('user_profile', 'step')},
            },
        ),
    ]
