# Generated by Django 5.2.7 on 2025-12-09 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0002_learningresource_userlearningprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='userskillprogress',
            name='milestone_achieved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userskillprogress',
            name='milestone_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userskillprogress',
            name='step_progress',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
