# Generated by Django 5.2.7 on 2025-12-09 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0003_userskillprogress_milestone_achieved_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('badge_type', models.CharField(choices=[('BRONZE', 'Bronze'), ('SILVER', 'Silver'), ('GOLD', 'Gold')], default='BRONZE', max_length=16)),
                ('required_progress_percent', models.PositiveIntegerField(default=100)),
                ('required_completed_steps', models.PositiveIntegerField(default=0)),
                ('required_streak_days', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achieved_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.milestone')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.userprofile')),
            ],
            options={
                'ordering': ['-achieved_at'],
                'unique_together': {('user_profile', 'milestone')},
            },
        ),
    ]
