# Generated by Django 5.2.7 on 2025-12-09 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0004_milestone_usermilestone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('RECOMMENDATION', 'Recommendation Quality'), ('UI_EXPERIENCE', 'User Interface'), ('FEATURE_REQUEST', 'Feature Request'), ('BUG_REPORT', 'Bug Report'), ('GENERAL', 'General Feedback')], default='GENERAL', max_length=20)),
                ('rating', models.PositiveIntegerField(blank=True, help_text='Rating from 1-5 stars', null=True)),
                ('comment', models.TextField(blank=True)),
                ('suggestion', models.TextField(blank=True, help_text='Suggestions for improvement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Feedback',
                'verbose_name_plural': 'User Feedback',
                'ordering': ['-created_at'],
            },
        ),
    ]